buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.0.2'
    }
}

apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.banoth.chatapp'
    compileSdk 33

    defaultConfig {
        applicationId "com.banoth.chatapp"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
}
