plugins {
    id 'com.android.application' version '8.0.2'
}

android {
    namespace 'com.banoth.chatapp'
    compileSdk 33

    defaultConfig {
        applicationId "com.banoth.chatapp"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    // Free Local Storage Database Engine
    implementation 'androidx.room:room-runtime:2.5.2'
    annotationProcessor 'androidx.room:room-compiler:2.5.2'
    
    // Free Google Authentication Plugin Layer
    implementation 'com.google.firebase:firebase-auth:22.1.1'
    implementation 'com.google.android.gms:play-services-auth:20.6.0'
    
    // Free Live AdMob Ads Integration
    implementation 'com.google.android.gms:play-services-ads:22.3.0'
}
