plugins {
    id 'com.android.application' version '8.0.2'
}

android {
    namespace 'com.banoth.chatapp'
    compileSdk 33

    defaultConfig {
        applicationId "com.banoth.chatapp"
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    // 100% Free Google Play Services AdMob SDK Core Library Integration
    implementation 'com.google.android.gms:play-services-ads:22.4.0'
    
    // Free Client-Side Firebase Authentication Platform Dependency Hooks
    implementation 'com.google.firebase:firebase-auth:22.1.1'
}
